add balls
Vad1mCSO2/blackknighttracker pull request #5
Opened 2024-12-26 19:05 UTC by morbing

add balls

2024-12-26 22:05 UTC, qsheltier requested changes
These balls are too small.

2024-12-26 22:49 UTC, morbing commented
> These balls are too small.

thanks. fixed.

2024-12-27 03:19 UTC, Vad1mCSO2 commented
Not approved

2024-12-27 03:19 UTC, closed without merging

2024-12-27 03:23 UTC, Vad1mCSO2 commented
The following reason: Off-Topic

2025-01-05 03:06 UTC, emipasta commented
pls reconsider